services:
  mongo:
    image: mongo
    container_name: maple-mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  auth:
    build: ./apps/auth
    container_name: maple-auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongo
